### ISSUE TITLE
Missing github CODEOWNERS file lets approval validation fail

### ISSUE THREAD

**Issue by hemeroc** [mergeability/mergeable#370]
**Description**

When creating a validation for approvals and setting `required: owners` to `true` the validation errors when there is no `.github/CODEOWNERS` file present. Which is a problem as this check is included in the organizational wide `mergeable` settings.

```json
- when: pull_request.*, pull_request_review.*
    name: 'PR has the required number of approvals'
    validate:
      - do: approvals
        min:
          count: 1
        required:
          owners: true
        block:
          changes_requested: true
```

**Actual behavior**

The validation fails with following error message:

```text
HttpError: Resource not accessible by integration
    at /app/node_modules/@octokit/request/dist-node/index.js:66:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Job.doExecute (/app/node_modules/bottleneck/light.js:405:18)
```

**Expected behavior**

* The validation does not fail but is ignored instead.

OR

* The validation can be marked as `optional`

**Comment by hemeroc** [comment]
After some investigation I think this occurs as some of the projects are set to `internal` instead of `public`.
I solved it by giving the app full read access to all repositories in the organization.
If that is the intended behavior the documentation on this could be improved but this issue can be closed.
