### ISSUE TITLE
Validator: INTERNAL ERROR

### ISSUE THREAD

**Issue by billburgess** [mergeability/mergeable#707]
Just got this working at the organization level and the first run that was using the organization file errored with this.

Input :
Settings : {}
Error : This is a mergeable bug, please report it on our issue tracker: https://github.com/mergeability/mergeable/issues/new

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Size.validateSettings (/app/lib/validators/validator.js:80:30)
    at Size.validateSettings (/app/lib/validators/validator.js:87:14)
    at Size.processValidate (/app/lib/validators/validator.js:45:12)
    at validateFuncCall (/app/lib/flex/lib/getValidatorPromises.js:4:74)
    at /app/lib/flex/lib/createPromises.js:8:21
    at Array.forEach (<anonymous>)
    at createPromises (/app/lib/flex/lib/createPromises.js:3:18)
    at getValidatorPromises (/app/lib/flex/lib/getValidatorPromises.js:6:10)
    at processWorkflow (/app/lib/flex/lib/processWorkflow.js:104:38)
```

**Comment by shine2lay** [comment]
from the stack trace, my immediate guess is that there maybe a typo in your config.

**Comment by billburgess** [comment]
That was it. Commented a bunch and it seems to work. Thanks.
