### ISSUE TITLE
Multiple code owners cause internal error

### ISSUE THREAD

**Issue by Alexander-Shukaev** [mergeability/mergeable#769]
❗ Validator: INTERNAL ERROR
Status ERROR

❗ Internal error!
Input :
Settings : {}
Error : This is a mergeable bug, please report it on our issue tracker: https://github.com/mergeability/mergeable/issues/new

```text
SyntaxError: Invalid regular expression: /^*/i: Nothing to repeat
    at new RegExp (<anonymous>)
    at createRegexToMatch (/workspace/lib/validators/options_processor/gitPattern.js:85:10)
    at GitPattern.checkIfPathMatches (/workspace/lib/validators/options_processor/gitPattern.js:41:19)
    at /workspace/lib/validators/options_processor/gitPattern.js:22:63
    at Array.find (<anonymous>)
    at /workspace/lib/validators/options_processor/gitPattern.js:22:45
    at Array.filter (<anonymous>)
    at Object.for (/workspace/lib/validators/options_processor/gitPattern.js:21:16)
    at /workspace/lib/validators/options_processor/owners.js:24:29
    at Array.forEach (<anonymous>)
```

```
* @org/team1 @org/team2
```

**Comment by andekande** [comment]
Hello,
can you please check if there is no space before the 'star' character.
Also there might be some hidden control-characters in that CODEOWNERS line. (before or after the *)
Also make sure its not the only line (maybe add a blank line at the end)
